= Tour of Heroes app
From Google

====

.Heroes App on StackBlitz
[cols="1,1"]
|===
a| App::
https://heroes-314.stackblitz.io

a| Source::
https://stackblitz.com/edit/heroes-314
|===

.NodeJS backend exported from API Express
[cols="1,1"]
|===
a| Building a Production Ready Node.js JSON API::
https://thinkster.io/tutorials/node-json-api

a| RealWorld example apps::
https://github.com/gothinkster/realworld
|===
====

== Steps

. Make changes to the application:
  https://angular.io/tutorial/toh-pt0#make-changes-to-the-application

. Create the heroes component:
  https://angular.io/tutorial/toh-pt1#create-the-heroes-component

. Show the HeroesComponent view:
  https://angular.io/tutorial/toh-pt1#show-the-heroescomponent-view

. Create a Hero interface:
  https://angular.io/tutorial/toh-pt1#create-a-hero-interface

. Show the hero object:
  https://angular.io/tutorial/toh-pt1#show-the-hero-object

. Format with the _UppercasePipe_:
  https://angular.io/tutorial/toh-pt1#format-with-the-uppercasepipe

. Edit the hero:
  https://angular.io/tutorial/toh-pt1#edit-the-hero

. Create mock heroes:
  https://angular.io/tutorial/toh-pt2#create-mock-heroes

. Displaying heroes:
  https://angular.io/tutorial/toh-pt2#displaying-heroes

. Master/Detail:
  https://angular.io/tutorial/toh-pt2#masterdetail

. Make the `HeroDetailComponent`:
  https://angular.io/tutorial/toh-pt3#make-the-herodetailcomponent

. Show the `HeroDetailComponent`:
  https://angular.io/tutorial/toh-pt3#show-the-herodetailcomponent

. Create the `HeroService`:
  https://angular.io/tutorial/toh-pt4#create-the-heroservice

. Provide the `HeroService`:
  https://angular.io/tutorial/toh-pt4#provide-the-heroservice

. Update `HeroesComponent`:
  https://angular.io/tutorial/toh-pt4#update-heroescomponent

. Observable data:
  https://angular.io/tutorial/toh-pt4#observable-data

. Show messages:
  https://angular.io/tutorial/toh-pt4#show-messages

. Add additional messages to hero service:
  https://angular.io/tutorial/toh-pt4#add-additional-messages-to-hero-service

. Add the `AppRoutingModule`:
  https://angular.io/tutorial/toh-pt5#add-the-approutingmodule

. Add `RouterOutlet`:
  https://angular.io/tutorial/toh-pt5#add-routeroutlet

. Add a navigation link (`routerLink`):
  https://angular.io/tutorial/toh-pt5#add-a-navigation-link-routerlink

. Add a dashboard view:
  https://angular.io/tutorial/toh-pt5#add-a-dashboard-view

. Navigating to hero details:
  https://angular.io/tutorial/toh-pt5#navigating-to-hero-details

. Routable `HeroDetailComponent`:
  https://angular.io/tutorial/toh-pt5#routable-herodetailcomponent

. Enable HTTP services:
  https://angular.io/tutorial/toh-pt6#enable-http-services

. Simulate a data server:
  https://angular.io/tutorial/toh-pt6#simulate-a-data-server

. Heroes and HTTP:
  https://angular.io/tutorial/toh-pt6#heroes-and-http

. Update heroes:
  https://angular.io/tutorial/toh-pt6#update-heroes

. Add a new hero:
  https://angular.io/tutorial/toh-pt6#add-a-new-hero

. Delete a hero:
  https://angular.io/tutorial/toh-pt6#delete-a-hero

. Search by name:
  https://angular.io/tutorial/toh-pt6#search-by-name

