= React - The Complete Guide (incl Hooks, React Router, Redux)
:source-highlighter: coderay
:icons: font
:toc: left
:toclevels: 4
Maximilian Schwarzmüller

====
Course on Udemy::
https://www.udemy.com/course/react-the-complete-guide-incl-redux/

Course source code on GitHub::
https://github.com/academind/react-complete-guide-course-resources
====

== 1. link:getting_started.html[Getting Started]

== 2. link:js_refresh.html[JavaScript Refresher]

== 3. link:react_basics.html[React Basics and Working With Components]

== 4. React Essentials - Deep Dive

=== 60. Module Introduction

In this course section, we will delve deeper into key React concepts covered previously. We will examine JSX and non-JSX code, revisit Components and State for better structure, and explore advanced state usage, patterns, and best practices. We'll start by enhancing the demo application from the last section, and later, we'll build a tic-tac-toe game to explore advanced concepts.

=== 61. You Don't Have To Use JSX!

This section discusses JSX code in React, emphasizing that while JSX is a non-standard feature not directly supported by browsers, it simplifies the development process. JSX code is transformed by a build process into browser-compatible code. Although it's possible to create React applications without JSX using the `createElement` method from React, this approach is more verbose and less intuitive. Most React projects, including those in this course, will utilize JSX for its convenience and readability. The text also highlights that using the non-JSX method requires no build process but is typically more complex. A practical example is provided, demonstrating how to create a root component using both JSX and the non-JSX approach while achieving the same result on screen.

=== 62. Working with Fragments

The discussion focuses on JSX and its requirement for a single parent element in a return statement. In an example using a `div` to wrap sibling elements, it is explained that removing the `div` leads to an error because JSX must return one parent element. This limitation is likened to JavaScript's inability to return multiple values from a function. To avoid unnecessary DOM elements, React provides a `Fragment` component, which can be used as a wrapper without rendering an actual element. Additionally, modern React projects allow for an even shorter syntax using empty tags to achieve the same effect without extra code or DOM elements.

====
Working with Fragments::
++++
<a href="https://github.com/academind/react-complete-guide-course-resources/blob/main/code/04%20Essentials%20Deep%20Dive/02-fragments/src/App.jsx" target="_blank">
04 Essentials Deep Dive/02-fragments</a>
++++
====