= Diagrams: RAG and Memory - A Comprehensive Dive
:source-highlighter: pygments
:icons: font
:toc: right

link:udemy_langchain.html[<Contents>]

---

== 89. Hands-on ~ Create Your First Simple Graph

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	process(process)
	__end__([<p>__end__</p>]):::last
	__start__ --> process;
	process --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 90. Hands-on ~ Understanding Reducers and Accumulating State

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	step_one(step_one)
	step_two(step_two)
	__end__([<p>__end__</p>]):::last
	__start__ --> step_one;
	step_one --> step_two;
	step_two --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

</div>
++++
---


== 91. Hands-on ~ Message State - The Chat Pattern

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	chat_node(chat_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> chat_node;
	chat_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 92. Hands-on ~ Multi-Node Pipelines - Chaining LLM Calls

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	analyze_node(analyze_node)
	enhance_node(enhance_node)
	finalize_node(finalize_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze_node;
	analyze_node --> enhance_node;
	enhance_node --> finalize_node;
	finalize_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 93. Exercise ~ Build Your First Node

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	generate_questions(generate_questions)
	answer_question(answer_question)
	__end__([<p>__end__</p>]):::last
	__start__ --> generate_questions;
	generate_questions --> answer_question;
	answer_question --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---



== 94. Hands-on ~ Full LangGraph Step-by-Step Workflow

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	analyze_sentiment(analyze_sentiment)
	generate_response(generate_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze_sentiment;
	analyze_sentiment --> generate_response;
	generate_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 96. Hands-on ~ Basic Routing with Literal Routing Types

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify(classify)
	handle_question(handle_question)
	handle_command(handle_command)
	handle_statement(handle_statement)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify;
	classify -. &nbsp;command&nbsp; .-> handle_command;
	classify -. &nbsp;question&nbsp; .-> handle_question;
	classify -. &nbsp;statement&nbsp; .-> handle_statement;
	handle_command --> __end__;
	handle_question --> __end__;
	handle_statement --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

</div>
++++
---


== 97. Hands-on ~ Conditional Looping

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	evaluate(evaluate)
	improve(improve)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> evaluate;
	evaluate -.-> finalize;
	evaluate -.-> improve;
	improve --> evaluate;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 98. Hands-on ~ Multipath Routing

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyze(analyze)
	urgent_complex(urgent_complex)
	urgent_simple(urgent_simple)
	normal_complex(normal_complex)
	normal_simple(normal_simple)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze;
	analyze -.-> normal_complex;
	analyze -.-> normal_simple;
	analyze -.-> urgent_complex;
	analyze -.-> urgent_simple;
	normal_complex --> __end__;
	normal_simple --> __end__;
	urgent_complex --> __end__;
	urgent_simple --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---


== 99. Hands-on ~ Cycles and Loops - Self-Correcting Code Writer

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	generate(generate)
	validate(validate)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> generate;
	generate --> validate;
	validate -. &nbsp;end&nbsp; .-> finalize;
	validate -.-> generate;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 100. Hands-on ~ Iterative Research Agent with Loops and Cycles

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	research(research)
	generate_questions(generate_questions)
	synthesize(synthesize)
	__end__([<p>__end__</p>]):::last
	__start__ --> research;
	generate_questions -.-> research;
	generate_questions -.-> synthesize;
	research --> generate_questions;
	synthesize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 102. Hands-on ~ Human Input - Interrupt for Approval

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	draft(draft)
	approval(approval<hr/><small><em>__interrupt = before</em></small>)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> draft;
	approval --> finalize;
	draft --> approval;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 103. Full Human in the Loop Workflow

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	submit(submit<hr/><small><em>__interrupt = before</em></small>)
	apply(apply)
	done(done)
	__end__([<p>__end__</p>]):::last
	__start__ --> submit;
	apply --> submit;
	submit -.-> apply;
	submit -.-> done;
	done --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 104. Hands-on ~ Checkpointing Deep Dive

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	chat(chat)
	__end__([<p>__end__</p>]):::last
	__start__ --> chat;
	chat --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---

== 105. Checkpoint Internals Deep Dive

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph LR;
	__start__([<p>__start__</p>]):::first
	analyze(analyze)
	summarize(summarize)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze;
	analyze --> summarize;
	summarize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---





////
---
++++
<div class="mermaid">
</div>
++++
---
////

++++
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true });
</script>
++++
