= Diagrams: Multi-Agent Systems with LangGraph and LangChain
:source-highlighter: pygments
:icons: font
:toc: right

link:udemy_langchain.html[<Contents>]

---

== 108. Hands-on ~ Tool Calling Agent

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	agent(agent)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> agent;
	agent -. &nbsp;end&nbsp; .-> __end__;
	agent -.-> tools;
	tools --> agent;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---


== 110. Hands-on ~ The Supervisor Agent

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	researcher(researcher)
	writer(writer)
	critic(critic)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	critic --> supervisor;
	researcher --> supervisor;
	supervisor -.-> critic;
	supervisor -.-> finalize;
	supervisor -.-> researcher;
	supervisor -.-> writer;
	writer --> supervisor;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---


== 111. Hands-on ~ Agent Handoffs in LangGraph

---
++++
<div class="mermaid">
---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	triage(triage)
	sales(sales)
	support(support)
	billing(billing)
	__end__([<p>__end__</p>]):::last
	__start__ --> triage;
	triage -. &nbsp;end&nbsp; .-> __end__;
	triage -.-> billing;
	triage -.-> sales;
	triage -.-> support;
	billing --> __end__;
	sales --> __end__;
	support --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
</div>
++++
---





////
---
++++
<div class="mermaid">

</div>
++++
---
////

++++
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true });
</script>
++++