= Progressive Web Apps (PWA) - The Complete Guide
:icons: font
:source-highlighter: pygments
:toc: right
:toclevels: 4

NOTE: http-server in Android Studio emulator: http://10.0.2.2:8080


== Understanding the App Manifest

=== Useful Links

|===

| Add to home screen (A2HS) - Browser Support | https://caniuse.com/web-app-manifest

| MDN Article on the Web App Manifest (includes List of all Properties) | https://developer.mozilla.org/en-US/docs/Web/Manifest

| A detailed Web App Manifest Explanation by Google | https://web.dev/add-manifest/

| More about the "Web App Install Banner" (including Requirements) |  https://web.dev/customize-install/

|===

=== Understanding App Manifest Properties

```json
include::02-app-manifest/manifest.json[]
```

== The Service Workers

|===

| The App Install Banner: | https://web.dev/customize-install/
| DevTools | https://developer.chrome.com/docs/devtools/
|===

NOTE: Make sure you enabled "Developer Mode" on your Device! You do that by tapping your Android Build Number (in the Settings) 7 times. 

== Promise and Fetch


=== Useful Resources

==== Promises

[cols="1,3"]
|===
| *Introduction to Promises (MDN):* | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
| *Introduction to Promises (Google):* | https://developers.google.com/web/fundamentals/getting-started/primers/promises
|===

==== Fetch API

[cols="1,3"]
|===
| *An Overview on MDN:* | https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
| *Detailed Usage Guide (MDN):* | https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
| *Detailed Usage Guide (and comparison with XMLHttpRequest):* | https://davidwalsh.name/fetch
| *Introduction to Fetch (Google):* | https://developers.google.com/web/updates/2015/03/introduction-to-fetch
|===

=== Assignment

==== Task 1

```js
  // Create a new Promise here and use setTimeout inside the function you pass to the constructor
  let promise = new Promise(
    function (resolve) {

      setTimeout(function () { // <- Store this INSIDE the Promise you created!
        // Resolve the following URL: https://swapi.co/api/people/1
        resolve('https://swapi.dev/api/people/1');
      }, 3000);

    }
  );

  promise.then(function (url) {
    // Handle the Promise "response" (=> the value you resolved) and returß a fetch()
    // call to the value (= URL) you resolved (use a GET request)
    return fetch(url, { mode: "no-cors" });
  }).then(function (response) {
    // Handle the response of the fetch() call and extract the JSON data, return that
    // and handle it in yet another then() block
    return response.json();
  }).then(function (data) {
    // Finally, output the "name" property of the data you got back (e.g. data.name) inside
    // the "output" element (see variables at top of the file)
    console.log('data:', data);
    output.innerHTML = data.name;
  });
```  
[WARNING]
====
sw.js:12 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://swapi.dev/api/people/1 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
====

==== Task 2

```js
  // Repeat the exercise with a PUT request you send to https://httpbin.org/put
  let promise = new Promise(
    function (resolve) {
      setTimeout(function () { // <- Store this INSIDE the Promise you created!        
        resolve('https://httpbin.org/put');
      }, 1000);
    }
  );

  // Make sure to set the appropriate headers (as shown in the lecture)
  // Send any data of your choice, make sure to access it correctly when outputting it
  // Example: If you send {person: {name: 'Max', age: 28}}, you access data.json.person.name
  // to output the name (assuming your parsed JSON is stored in "data")
  promise.then(function (url) {
    return fetch(url, {
      method: "PUT", 
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify({
        name: "John"
      })
    });
  }).then(function (response) {
    return response.json();
  }).then(function (data) {
    console.log('data:', data);
    output.innerHTML = JSON.parse(data.data).name;
  });
```

==== Task 3

```js
  // Handle the error in catch()

  let promise = new Promise(
    function (resolve) {
      setTimeout(function () { 
        resolve('https://swapi.dev/api/people/1');
      }, 500);
    }
  );

  promise.then(function (url) {
    return fetch(url, { mode: "no-cors" });
  }).then(function (response) {
    return response.json();
  }).then(function (data) {
    console.log('-- data:', data);
    output.innerHTML = data.name;
  }).catch(function (err) {
    console.log('-- err:', err);
  });
```
==== Task 4

```js
  // Handle the error as a second argument to then()
  let promise = new Promise(
    function (resolve) {
      setTimeout(function () { 
        resolve('https://swapi.dev/api/people/1');
      }, 500);
    }
  );

  promise.then(function (url) {
    return fetch(url);
  },
  function (err) {
    console.log('-- err:', err);
  }).then(function (response) {
    return response.json();
  }).then(function (data) {
    console.log('-- data:', data);
    output.innerHTML = data.name;
  });
```

== Service Workers - Caching

=== Useful Resources

[cols="1,3"]
|===
| *About Cache Persistence and Storage Limits:* | https://jakearchibald.com/2014/offline-cookbook/#cache-persistence
| *Learn more about Service Workers:* |  https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
|===

=== Static and Dynamic Caching

```js
include::05-sw-caching/sw-caching-01--updated-project/sw-caching-01--updated-project/public/sw.js[]
```

== Service Workers - Advanced Caching

=== Useful Resources

[cols="1,3"]
|===
| *Offline Cookbook:* | https://jakearchibald.com/2014/offline-cookbook/
| *Advanced Caching Guide:* | https://www.afasterweb.com/2017/01/31/upgrading-your-service-worker-cache/
| *Mozilla Strategy Cookbook:* | https://serviceworke.rs/strategy-cache-and-update_service-worker_doc.html
|===

=== Offering "Cache on Demand"

```js
function onSaveButtonClicked(event) {
  console.log('clicked');
  if ('caches' in window) {
    caches.open('user-requested')
    .then(function (cache) {
      cache.add('https://httpbin.org/get');
      cache.add('/src/images/sf-boat.jpg');
    });
  }
}
```

=== Providing an Offline Fallback Page

```js
self.addEventListener('fetch', function(event) {
  event.respondWith(
    caches.match(event.request)
      .then(function(response) {
        if (response) {
          return response;
        } else {
          return fetch(event.request)
            .then(function(res) {
              return caches.open(CACHE_DYNAMIC_NAME)
                .then(function(cache) {
                  cache.put(event.request.url, res.clone());
                  return res;
                })
            })
            .catch(function(err) {
              return caches.open(CACHE_STATIC_NAME)
                .then(function (cache) {
                  return cache.match('/offline.html');  <1>
                });
            });
        }
      })
  );
});
```
<1> Return offline page stored in a static cache

=== Strategy: Cache with Network Fallback

This is what we implemented above.

=== Strategy: Network with Cache Fallback

```js
self.addEventListener('fetch', function(event) {
  event.respondWith(
    fetch(event.request)
      .then(function (res) {
        return caches.open(CACHE_DYNAMIC_NAME)
          .then(function(cache) {
            cache.put(event.request.url, res.clone());
            return res;
          })
      })
      .catch(function (err) {
        return caches.match(event.request);
      })
  );
});
```

=== Strategy: Cache then Network

.feed.js
```js
var url = 'https://httpbin.org/get';
var networkDataReceived = false;

fetch(url)
  .then(function(res) {
    return res.json();
  })
  .then(function(data) {
    networkDataReceived = true;
    console.log('From web', data);
    clearCards();
    createCard();
  });

if ('caches' in window) {
  caches.match(url)
    .then(function (response) {
      if (response) {
        return response.json();
      }
    })
    .then(function (data) {
      console.log('From cache', data);
      if (!networkDataReceived) {
        clearCards();
        createCard();
      }
    })
}
```

=== Cache then Network & Dynamic Caching

.sw.js
```js
self.addEventListener('fetch', function(event) {
  event.respondWith(
    caches.open(CACHE_DYNAMIC_NAME)
      .then(function (cache) {
        return fetch(event.request)
          .then(function (res) {
            cache.put(event.request, res.clone());
            return res;
          })
      })
  );
});
```

=== Cache then Network with Offline Support

.sw.js
```js
self.addEventListener('fetch', function(event) {
  var url = 'https://httpbin.org/get';

  if (event.request.url.indexOf(url) > -1) {
    event.respondWith(
      caches.open(CACHE_DYNAMIC_NAME)
        .then(function (cache) {
          return fetch(event.request)
            .then(function (res) {
              cache.put(event.request, res.clone());
              return res;
            })
        })
    );
  } else {
    event.respondWith(
      caches.match(event.request)
        .then(function(response) {
          if (response) {
            return response;
          } else {
            return fetch(event.request)
              .then(function(res) {
                return caches.open(CACHE_DYNAMIC_NAME)
                  .then(function(cache) {
                    cache.put(event.request.url, res.clone());
                    return res;
                  })
              })
              .catch(function(err) {
                return caches.open(CACHE_STATIC_NAME)
                  .then(function (cache) {
                    return cache.match('/offline.html');
                  });
              });
          }
        })
      );
  }

});
```

== IndexedDB and Dynamic Data

.utility.js
```js
include::07-idb/idb-02--added-idb-package/public/src/js/utility.js[]
```

=== Useful Resources

[cols="1,3"]
|===
| *IDB on Github:* | https://github.com/jakearchibald/idb
| *IndexedDB explained on MDN:* | https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
| *Alternative to IDB:* | http://dexie.org/
|===

== Creating a Responsive User Interface

=== Useful Resources

[cols="1,3"]
|===
| *Responsive Design Basics by Google:* | https://web.dev/learn/design/
| *Responsive Design Patterns (Google):* | https://web.dev/learn/design/ui-patterns/
| *Responsive Images (Google):* | https://web.dev/learn/design/responsive-images/
| *Using CSS Media Queries:* | https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries
| *Responsive Images (MDN):* | https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
| *Responsive Images in CSS:* | https://css-tricks.com/responsive-images-css/
| *Using CSS Animations:* | http://learn.shayhowe.com/advanced-html-css/transitions-animations/
|===

== Background Sync

=== Useful Resources

.Firebase Functions
[cols="1,3"]
|===
| *Firebase Pricing:* | https://firebase.google.com/pricing
| *Firebase Console:* | https://console.firebase.google.com
| *Firebase Hosting:* | https://firebase.google.com/docs/hosting
| *Introducing Background Sync:* | https://developer.chrome.com/blog/background-sync/
| *A Basic Guide to Background Sync:* | https://ponyfoo.com/articles/backgroundsync
| *Cloud Functions for Firebase:* | https://firebase.google.com/docs/functions/
| *Create and Deploy Your First Cloud Functions:* | https://firebase.google.com/docs/functions/write-firebase-functions
|===

.Realtime Database
[cols="1,3"]
|===
| *Saving Data in Realtime Database:* | https://firebase.google.com/docs/database/admin/save-data
| `push():` | https://firebase.google.com/docs/reference/js/database#push
|===

=== feed.js

```js
var MY_FIREBASE_ID = '...'; <7>
var MY_TEST_IMAGE_URL = '...'; <8>

function sendData() { <2>
  fetch(MY_FIREBASE_ID + '.firebasedatabase.app/posts.json', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({
      id: new Date().toISOString(),
      title: titleInput.value,
      location: locationInput.value,
      image: MY_TEST_IMAGE_URL
    })
  })
    .then(function(res) {
      console.log('Sent data', res);
      updateUI();
    });
}

form.addEventListener('submit', function(event) { <6>
  event.preventDefault();

  if (titleInput.value.trim() === '' || locationInput.value.trim() === '') {
    alert('Please enter valid data!');
    return;
  }

  closeCreatePostModal();

  if ('serviceWorker' in navigator && 'SyncManager' in window) {
    navigator.serviceWorker.ready <3>
      .then(function(sw) {
        var post = {
          id: new Date().toISOString(),
          title: titleInput.value,
          location: locationInput.value
        };
        writeData('sync-posts', post)
          .then(function () {
            return sw.sync.register('sync-new-posts')  <4>
          })
          .then(function () {
            var snackbarContainer = document.querySelector("#confirmation-toast"); <5>
            var data = {message: "Your Post was saved for syncing!"};
            snackbarContainer.MaterialSnackbar.showSnackbar(data);
          }).catch(function (err) {
            console.log(err);
          });
      });
  } else {
    sendData(); <1>
  }
});
```

<1> отправляем данные если браузер не поддерживает background sync
<2> отправка данных
<3> background sync
<4> регистрируем background sync event tag
<5> показать toast что в оффлайне мы сохранили сообщение в idb
<6> background sync происходит по сабмиту формы
<7> id of my firebase
<8> url of my test image

=== sw.js

```js
var MY_FIREBASE_ID = '...'; <1>
var MY_TEST_IMAGE_URL = '...'; <3>

self.addEventListener('sync', function(event) {
  console.log('[Service Worker] Background syncing', event);
  if (event.tag === 'sync-new-posts') {
    console.log('[Service Worker] Syncing new Post');
    event.waitUntil(
      readAllData('sync-posts')
        .then(function(data) {
          for (var dt of data) {
            fetch(MY_FIREBASE_ID + '.firebasedatabase.app/posts.json', { <4>
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
              },
              body: JSON.stringify({
                id: dt.id,
                title: dt.title,
                location: dt.location,
                image: MY_TEST_IMAGE_URL
              })
            })
              .then(function(res) {
                console.log('Sent data', res);
                if (res.ok) {
                  deleteItemFromData('sync-posts', dt.id); <2>
                }
              })
              .catch(function (err) {
                console.log('Error while sending data', err);
              });
          }
        })
    );
  }

});
```

<1> id of my firebase
<2> bug here - async call cannot work with loop variable
<3> url of my test image
<4> когда мы заменили этот url на функцию firebase `storePostData` возникла проблема CORS

=== functions

```js
const functions = require("firebase-functions");
var admin = require('firebase-admin');
var cors = require('cors')({ origin: true });

var serviceAccount = require("./pwagram-fb-key.json");
var MY_DB_URL = '...'; <1>

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: MY_DB_URL
});

exports.storePostData = functions.https.onRequest((request, response) => {
    cors(request, response, function () {
        var reqBody = request.body;
        functions.logger.info('-- reqBody:', reqBody, '.'); <2>
        var newPost = {
            id: reqBody.id,
            title: reqBody.title,
            location: reqBody.location,
            image: reqBody.image
        };
        functions.logger.info('-- newPost:', newPost, '.');

        admin.database().ref('posts').push(newPost)
            .then(function () {
                response.status(201).json({ message: 'Data stored', id: request.body.id });
            })
            .catch(function (err) {
                response.status(500).json({ error: err });
            });
    });    
    //   response.send("Hello from Firebase!");
});
```

<1> url of my realtime database
<2> последний элемент лога пусть будет просто строкой, иначе он может пропасть из лога :-(

////
<1> интересно, почему эта библиотека не добавляет заголовок `Access-Control-Allow-Origin` ?

[WARNING]
.Error in Chrome
====
Access to fetch at `https://<MY_FIREBASE_APP>.web.app/storePostData` from origin `http://127.0.0.1:8080` has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No `Access-Control-Allow-Origin` header is present on the requested resource. If an opaque response serves your needs, set the request's mode to `no-cors` to fetch the resource with CORS disabled.
====
////

== Web Push Notifications