= Pro Angular 6
:toc: right
:toclevels: 4
:source-highlighter: pygments
:pygments-style: xcode
:source-language: js
:icons: font
Adam Freeman

[cols="1,3"]
|===
| Angular          | https://angular.io/
| Angular CLI      | https://cli.angular.io/
| Angular Material | https://material.angular.io/
| Angular Tutorial | https://angular.io/start
| Book Code        | https://github.com/Apress/pro-angular-6
|===

== CHAPTER 2. Your First Angular App

[cols="1,3"]
|===
| Angular CLI          | npm install --global @angular/cli
| Creating the Project | ng new todo
| Adding the Bootstrap CSS Package | npm install bootstrap
|===

== CHAPTER 7. SportsStore: A Real Application

[cols="1,3"]
|===
| Path | /mnt/disk2/home/egor/prog/ng-lists/books/
| File | src/app/app.component.html
|===

=== Adding the CSS Style Sheets to the Application

[cols="1,1"]
|===

a| Bootstrap::
https://getbootstrap.com/

a| Bootstrap widgets::
https://ng-bootstrap.github.io/

```sh
ng add @ng-bootstrap/ng-bootstrap
```

|===

.angular.json
```json
    "styles": [
      "src/styles.css",
      "node_modules/bootstrap/dist/css/bootstrap.min.css",
      "node_modules/font-awesome/css/font-awesome.min.css"
    ],
```

angular.json::
https://angular.io/guide/workspace-config

=== Starting the Data Model

==== Creating the Model Repository

.Listing 7-11
```ts
import { Injectable } from "@angular/core";
import { Product } from "./product.model";
import { StaticDataSource } from "./static.datasource";

@Injectable()
export class ProductRepository {

    private products: Product[] = [];
    private categories: string[] = [];

    constructor(private dataSource: StaticDataSource) {
        dataSource.getProducts().subscribe(data => {
            this.products = data;
            this.categories = data
                .map(p => p.category)
                .filter((c, index, array) => array.indexOf(c) == index).sort(); <1>
        });
    }

    getProducts(category: string = null): Product[] { <2>
        return this.products
            .filter(p => 
                category == null || 
                category == p.category);
    }

    getProduct(id: number): Product {
        return this.products.find(p => <3>
            p.id == id);
    }

    getCategories(): string[] {
        return this.categories;
    }
}
```
====
<1> `array.indexOf` выдает индекс первого вхождения, то есть таким образом удаляются дубликаты 
<2> Для параметра `null` возвращается весь список
<3> В этом фрагменте используются методы массива `map, filter, find`
====