= Ionic 5
:icons: font
:source-highlighter: pygments
:toc: right
:toclevels: 4
:example-caption: Note
Andreas Dormann

Ionic CLI::
https://ionicframework.com/docs/cli

[cols="1,1"]
|===

a| 3.5 The side menu app for our book project
a| `ionic start bob-tours sidemenu --type=angular`

a| 4.2 Generate pages
a| `ionic generate page pages/Favorites`

a| 5.2.2. Create a service
a| `ionic g service services/bob-tours`

|===

== 5. Services & Storage

=== 5.1. Database Backend with Google Firebase

=== 5.2. An HTTPClient Service

==== Programming the data access

Communicating with backend services using HTTP::
https://angular.io/guide/http

.bob-tours.service.ts
```ts
include::05/5.6/src/app/services/bob-tours.service.ts[]
```

== 7. Form validation

See link:InputValidationSample.html[Input Validation Sample]

=== 7.3. Implementation

=== 7.3.1. Setting up the ReactiveFormsModule

=== 7.3.2. Preparing the form validation and messages

== 11. Debugging & Testing

Ionic Testing::
https://ionicframework.com/docs/angular/testing

Enappd Tutorial on Ionic Testing::
https://enappd.com/blog/beginners-guide-to-ionic-angular-unit-testing-part-1/151/

=== 11.1. Health Check with Ionic Doctor

----
ionic doctor check
----

=== 11.2. Strictly Typing!

==== TypeScript and its advantages

==== Create classes

----
$ ionic g class models/category/category
$ ionic g class models/tour/tour
----

==== Use classes

