= Angular (Full App) with Angular Material, Angularfire & NgRx
:icons: font
:source-highlighter: pygments
:pygments-style: xcode
:toc: right
:toclevels: 4
Maximilian Schwarzmüller

https://academind.com/

== Section 3: Angular Material

TIP: *Assignment:* Login screen with validation and reactive form

=== Useful Links

Angular Material Setup Docs:: https://material.angular.io/guide/getting-started
Angular Material Component Docs:: https://material.angular.io/components/categories
Angular Material Github Repo:: https://github.com/angular/material2
@angular/flex-layout Docs:: https://github.com/angular/flex-layout
Flexbox Guide:: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Flexbox Video:: https://academind.com/learn/css/understanding-css/flexbox-basics-container

=== Template-Driven Forms

==== signup.component.html

====
```html
include::fitness-tracker/src/app/auth/signup/signup.component.html[]
```
====

==== signup.component.ts

====
```ts
include::fitness-tracker/src/app/auth/signup/signup.component.ts[]
```
====

==== signup.component.css

====
```css
include::fitness-tracker/src/app/auth/signup/signup.component.css[]
```
====

=== Reactive Forms

==== login.component.html

====
```html
include::fitness-tracker/src/app/auth/login/login.component.html[]
```
====

==== login.component.ts

====
```ts
include::fitness-tracker/src/app/auth/login/login.component.ts[]
```
====

==== login.component.css

====
```css
include::fitness-tracker/src/app/auth/login/login.component.css[]
```
====


== Section 4: Diving Deeper into Angular Material

- 39. Adding Navigation & a Sidenav
- 40. Working on the Sidenav and Toolbar
- 41. Styling the Sidenav
- 42. Making the Page Responsive
- 43. Adding Navigation Items
- 44. Splitting the Navigation Into Components
- 45. Working on the Welcome Screen
- 46. Adding a Tabs Component

=== Adding some "Cards"

==== new-training.component.html

====
```html
include::fitness-tracker/src/app/training/new-training/new-training.component.html[]
```
====

=== Adding a Spinner to the Training Screen

==== training.component.html

====
```html
include::fitness-tracker/src/app/training/training.component.html[]
```
====
