= AngularFire

====
Add Firebase to your JavaScript project::
https://firebase.google.com/docs/web/setup

```
ng add @angular/fire
```
====

____
AngularFire::
https://github.com/angular/angularfire

AngularFire Quickstart::
https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md
____

.firestore
____
+2.+ Documents in AngularFirestore::
https://github.com/angular/angularfire/blob/master/docs/firestore/documents.md

+3.+ Collections in AngularFirestore::
https://github.com/angular/angularfire/blob/master/docs/firestore/collections.md

+4.+ Querying Collections in AngularFirestore::
https://github.com/angular/angularfire/blob/master/docs/firestore/querying-collections.md

Offline Data in Firestore::
https://github.com/angular/angularfire/blob/master/docs/firestore/offline-data.md
____

.auth
____
+5.+ Getting started with Firebase Authentication::
https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md
____

.rtdb
____
+2.+ Retrieving data as objects::
https://github.com/angular/angularfire/blob/master/docs/rtdb/objects.md

+3.+ Retrieving data as lists::
https://github.com/angular/angularfire/blob/master/docs/rtdb/lists.md

+4.+ Querying lists::
https://github.com/angular/angularfire/blob/master/docs/rtdb/querying-lists.md
____

.functions
____
AngularFireFunctions::
https://github.com/angular/angularfire/blob/master/docs/functions/functions.md
____

.ionic
____
Installation and Setup with Ionic CLI::
https://github.com/angular/angularfire/blob/master/docs/ionic/cli.md

Using AngularFire with Ionic 3::
https://github.com/angular/angularfire/blob/master/docs/ionic/v3.md

Authentication::
https://github.com/angular/angularfire/blob/master/docs/ionic/authentication.md
____

.storage
____
AngularFireStorage::
https://github.com/angular/angularfire/blob/master/docs/storage/storage.md
____

.messaging
____
AngularFireMessaging::
https://github.com/angular/angularfire/blob/master/docs/messaging/messaging.md
____

.analytics
____
Getting started with Google Analytics::
https://github.com/angular/angularfire/blob/master/docs/analytics/getting-started.md
____

.universal
____
Getting started with AngularFire and Universal::
https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md

Deploying your Universal application on Cloud Functions for Firebase::
https://github.com/angular/angularfire/blob/master/docs/universal/cloud-functions.md

Prerendering your Universal application::
https://github.com/angular/angularfire/blob/master/docs/universal/prerendering.md
____

.remote-config
____
Getting started with Remote Config β::
https://github.com/angular/angularfire/blob/master/docs/remote-config/getting-started.md
____

.performance
____
Getting started with Performance Monitoring::
https://github.com/angular/angularfire/blob/master/docs/performance/getting-started.md
____
