= Reactive Patterns with RxJS for Angular
:icons: font
:source-highlighter: pygments
:toc: right
:toclevels: 4
:example-caption!: 
Lamis Chebbi


== Chapter 1. The Power of the Reactive Paradigm

- *Observables:* These are a representation of the data streams that notify the observers of any change.
- *Observers:* These are the consumers of the data streams emitted by observables.

=== Using RxJS in Angular and its advantages

==== The HTTP client module

.HttpClient.get() method
```ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '@env/environment';

const BASE_PATH = environment.basePath;

@Injectable()
export class RecipesService {
	constructor(private http: HttpClient) { }
	getRecipes(): Observable<Recipe[]> {
		return this.http.get<Recipe[]>(`${BASE_PATH}/recipes/search/all`); <1>
	}
}
```

<1> возвращаем `Observable` для которого впоследствии можно выполнить `subscribe`

[NOTE]
====
- Observables are cancellable, so you can cancel the HTTP request whenever you want by calling the unsubscribe method.
- Also, you can retry HTTP requests when an error occurs or an exception is thrown.
- The server's response cannot be mutated by observables, although this can be the case when chaining `then()` to promises.
====

==== The router module

https://angular.io/api/router/Event

.RouterEvent
```ts
include::snip01/CustomRouteService_1.ts[]
```

.NavigationStart
```ts
include::snip01/CustomRouteService_2.ts[]
```

===== The activated route

.ActivatedRoute
```ts
include::snip01/ActivatedRoute.ts[]
```

.RecipesComponent
```ts
include::snip01/RecipesComponent.ts[]
```

==== Reactive forms

.FormControl
```ts
include::snip01/FormControl.ts[]
```

.MyComponent
```ts
include::snip01/MyComponent.ts[]
```

==== The event emitter

.EventEmitter
```ts
include::snip01/EventEmitter.ts[]
```

.RecipesComponent
```ts
include::snip01/RecipesComponent_2.ts[]
```

==== The async pipe

```html+ng2
<div *ngIf="data$ | async"></div>
```

== Chapter 2. RxJS 7 – The Major Features

=== Understanding the toPromise() deprecation

.Last value
```ts
include::snip02/Observable_1.ts[]
```

.Undefined value
```ts
include::snip02/Observable_2.ts[]
```

==== The firstValueFrom() method

```ts
include::snip02/firstValueFrom.ts[]
```

==== The lastValueFrom() method

```ts
include::snip02/lastValueFrom.ts[]
```

==== Empty errors

.No elements in sequence
```ts
include::snip02/emptyErrors.ts[]
```

.defaultValue
```ts
include::snip02/defaultValue.ts[]
```

== Chapter 4: Fetching Data  as Streams

== Chapter 5. Error Handling

.See also:
====
- How to retry an HTTP request in Angular (with plenty of code examples) +
  https://danielk.tech/home/angular-retry-an-http-request
  
- Ionic 5 Make HTTP Calls and Handle Responses Easily Using an Interceptor +
  https://www.freakyjolly.com/ionic-4-make-http-calls-and-handle-responses-easily-using-an-interceptor/
====

=== Exploring error handling patterns and strategies

`from` operator::
https://rxjs.dev/api/index/function/from#description